#!/usr/bin/env bash
# This script displays list of currently running process
# Must show all process, for all users, including those which might not have a TTY
# Display a user-oriented format
# Show process hierachy 
# Display a user-oriented list of currently running processes
ps -a -x -u -f
