#!/usr/bin/env bash
# Create PID file and handle signals

# Create PID file in /var/run
sudo bash -c 'echo $$ > /var/run/codingschoolscript.pid'

# Trap signals and define cleanup actions
trap "sudo rm -f /var/run/codingschoolscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/codingschoolscript.pid; echo I hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT

# Infinite loop displaying a message
while :
do
    echo "To infinity and beyond"
    sleep 2
done

