#!/usr/bin/env bash
# Create PID file and handle signals

# Create PID file in /var/run
echo $$ > /var/run/myscript.pid

# Trap signals and define cleanup actions
trap 'cleanup' SIGTERM SIGQUIT
trap 'echo Y U no love me?!' SIGINT

# Function to clean up and terminate script
cleanup() {
    rm -f /var/run/myscript.pid
    echo "I hate the kill command"
    exit
}

# Infinite loop displaying a message
while :
do
    echo "To infinity and beyond"
    sleep 2
done

