#!/usr/bin/env bash
# This script displays username, user id, and home directory path from /etc/passwd

while IFS=':' read -r username x userid x homepath x; do
    echo "$username:$userid:$homepath"
done </etc/passwd

