#!/usr/bin/env bash
# This script tells a story based on the content of /etc/passwd

while IFS=':' read -r username x userid groupid desc homepath shell; do
    echo "The user $username is part of the $groupid gang, lives in $homepath and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $desc"
done </etc/passwd

