#!/usr/bin/env bash

# This script changes the IP resolution for localhost and facebook.com

# Check if running as root
if [[ $(id -u) -ne 0 ]]; then
    echo "Please run this script as root."
    exit 1
fi

# Update /etc/hosts file
echo "Changing localhost IP..."
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts

echo "Changing facebook.com IP..."
sed -i 's/\([[:digit:]]\+\.\)\{3\}[[:digit:]]\+ facebook.com/8.8.8.8 facebook.com/' /etc/hosts

echo "IP configuration changed successfully."

